_wandb:
    value:
        cli_version: 0.23.0
        e:
            z3y8cecl2p2ag0zjvg21hr1a9wlirtgy:
                args:
                    - --n_variables
                    - "3"
                    - --max_degree
                    - "3"
                    - --max_nodes
                    - "12"
                    - --mcts_simulations
                    - "200"
                    - --episodes_per_epoch
                    - "100"
                    - --epochs
                    - "200"
                    - --batch_size
                    - "256"
                    - --lr
                    - "0.0001"
                    - --num_workers
                    - "32"
                    - --checkpoint_path
                    - codes/scripts/runs/polynomial_net_complexity.pth
                    - --save_path
                    - codes/scripts/runs/polynomial_net_interesting.pth
                    - --complexity_start
                    - "2"
                    - --complexity_end
                    - "6"
                codePath: codes/scripts/polynomial_train_interesting.py
                codePathLocal: codes/scripts/polynomial_train_interesting.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "424418349056"
                email: zengrf2000@gmail.com
                executable: /home/ubuntu/miniconda3/envs/binary-forms/bin/python
                git:
                    commit: 9727d20732ceed34eac108c76e23316df32c4981
                    remote: https://github.com/YiwenAI/OpenTensor.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-1f93bb86-8101-69c5-c812-a1141aa19957
                host: ip-172-31-24-232
                memory:
                    total: "33263812608"
                os: Linux-6.8.0-1021-aws-x86_64-with-glibc2.35
                program: /home/ubuntu/random/src/OpenTensor/codes/scripts/polynomial_train_interesting.py
                python: CPython 3.10.18
                root: /home/ubuntu/random/src/OpenTensor
                startedAt: "2025-11-30T07:29:36.460831Z"
                writerId: z3y8cecl2p2ag0zjvg21hr1a9wlirtgy
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
complexity_end:
    value: 6
complexity_start:
    value: 2
curriculum_type:
    value: interesting_patterns
episodes_per_epoch:
    value: 100
epochs:
    value: 200
lr:
    value: 0.0001
max_degree:
    value: 3
max_nodes:
    value: 12
mcts_simulations:
    value: 200
n_variables:
    value: 3
